microservices/video_service/app/models.py
from flask_pymongo import ObjectId


class Video:

    def __init__(self, db, _id, title, description, genre, release, director, actor, duration, embed_code, thumbnail):
        self.db = db
        self._id = _id
        self.title = title
        self.description = description
        self.genre = genre
        self.release = release
        self.director = director
        self.actor = actor
        self.duration = duration
        self.embed_code = embed_code
        self.thumbnail = thumbnail

    def save_to_db(self):
        video_data = {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'genre': self.genre,
            'release': self.release,
            'director': self.director,
            'actor': self.actor,
            'duration': self.duration,
            'embed_code': self.embed_code,
            'thumbnail': self.thumbnail
        }
        result = self.db.video_collection.insert_one(video_data)
        return str(result.inserted_id)

    @classmethod
    def find_by_id(cls, db, video_id):
        return db.video_collection.find_one({'id': video_id})

    @classmethod
    def find_attribute_by_id(cls, db, video_id, attribute):
        video = db.video_collection.find_one({'_id': ObjectId(video_id)})
        return video[attribute] if video and attribute in video else None

microservices/video_service/app/routes.py
from flask import Flask, jsonify, render_template, session, request, Blueprint
from datetime import datetime, timezone, timedelta
from microservices.video_service.app.models import Video
import db

video_bp = Blueprint('video', __name__)


def stringify_data(data, include_fields=None):
    # If fields are not provided, include all fields
    include_fields = include_fields or data.keys()

    # Only the specified fields will be included
    filtered_data = {field: data[field] for field in include_fields if field in data}

    # Convert to string
    if '_id' in filtered_data:
        filtered_data['_id'] = str(filtered_data['_id'])
    return filtered_data


@video_bp.route('/')
def display_video_selection():
    all_videos = db.video_collection.find()

    video_list = list(all_videos)

    return render_template('videos.html', videos=video_list)


@video_bp.route('/<int:video_id>/')
def video_player(video_id):
    # Fetch the video details based on the video_id from your data source (e.g., MongoDB)
    # For now, let's assume you have a function get_video_by_id(video_id)
    video = Video.find_by_id(db, video_id)
    if video:
        return render_template('video_player.html', video=video)
    else:
        return "Video not found", 404

microservices/video_service/templates/video_player.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Video Player</title>
</head>
<body>
    {{ video.embed_code | safe }}
</body>
</html>

microservices/video_service/templates/videos.html
<!-- videos.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video Catalog</title>
</head>
  <!-- based on the CSS in this forum https://www.shecodes.io/athena/39603-how-to-place-an-image-inside-a-grid-box-in-css-->
<style>
.grid-container {
  display: grid;

  grid-template-columns: repeat(3, 1fr);
  grid-gap: 10px;
  grid-template-areas:
    "image1 image1 image1"
    "text text text";
}

.image1 {
  grid-area: image1;
}

img {
  max-width: 100%;
  height: auto;
}
</style>
<body>
    <h1>Video Catalog</h1>
    <div class="grid-container">
        {% for video in videos %}
                <div>
                    <h2>{{ video.title }}</h2>
                    <a href="{{ url_for('video.video_player', video_id=video.id) }}">
                        <img src="{{ url_for('static', filename=video.thumbnail) }}" style="width:100%" alt="{{ video.title }} Thumbnail" >
                    </a>
                    <!-- Other video details... -->
                    {{ video.release_date }}
                    {{ video.duration }}
                </div>

        {% endfor %}
    </div>
</body>
</html>